### ISSUE TITLE
Check compliance with SCIM specs

### ISSUE THREAD

**Issue by dacrome** [osiam/osiam#25]
The compliance with the SCIM [core schema](https://tools.ietf.org/html/draft-ietf-scim-core-schema-22) and [api](https://tools.ietf.org/html/draft-ietf-scim-api-19) spec needs to be checked.
This issue invites everyone to check the spec against our implementation in [osiam](https://github.com/osiam/osiam).
The following incompatibilities already have been found:
- [ ] https://github.com/osiam/osiam/issues/309
- [ ] [Scim Schema extensions does not support object's](https://github.com/osiam/osiam/issues/131)
- [ ] [Add /Schemas endpoint](https://github.com/osiam/osiam/issues/73)
- [ ] [Add /RessourceTypes endpoint](https://github.com/osiam/osiam/issues/72)
- [ ] [Set GroupRef Type](https://github.com/osiam/osiam/issues/67)
- [x] [Update urn schema URIs](https://github.com/osiam/scim-schema/issues/141)
- [x] [Wrong schema for SCIMSearchResult](https://github.com/osiam/resource-server/issues/33)
- [x] [Remove PATCH'ing of resources](https://github.com/osiam/osiam/issues/21)
- [x] [Resources with only 'primary' sub-attribute set should be rejected](https://github.com/osiam/osiam/issues/62)
- [x] [Error responses not SCIM compliant](https://github.com/osiam/resource-server/issues/37)
- [x] [Returning the "id" attribute is mandatory](https://github.com/osiam/osiam/issues/151)

This is a living issue. Please add issues/PRs if I missed them or if new issues/PRs are created to fulfill this issue.

**Comment by tkrille** [comment]
> Update User with PATCH: add and delete same email address depends on the order

Actually, I thought that we remove the PATCH functionality: #21

**Comment by wallner** [comment]
Error responses are now SCIM compliant.

**Comment by dacrome** [comment]
Added `Scim Schema extensions does not support object's`

**Comment by dacrome** [comment]
Added #151

**Comment by tkrille** [comment]
I've added https://github.com/osiam/osiam/issues/309 to the list of compliance issues.
