### ISSUE TITLE
OSIAM 3.0 Roadmap

### ISSUE THREAD

**Issue by dacrome** [osiam/osiam#42]
This is a meta issue to track which issues and tasks need to be done for the OSIAM 3.0 release. This is a living issue so make sure new issues are added here and closed are set to done. If you are not agree with this list please comment or change.
# [osiam](https://github.com/osiam/osiam)

[Must-Haves for 3.0](https://github.com/osiam/osiam/milestones/3.0)
- [ ] #5 
- [x] #6 
- [x] #10 
- [ ] #15 
- [ ] #21 
- [ ] #25 
- [ ] #34 
- [x] #35 
- [ ] #36 
- [ ] #45 
- [ ] #46 
- [ ] #47 
- [ ] #48 
- [ ] #49 
- [ ] #50 
- [ ] #51 
- [x] #56  
- [x] #57 
- [x] #66 
- [ ] #69 
- [x] #70 
- [x] #74 
- [ ] #83
# [connector4java](https://github.com/osiam/connector4java)

[Must-Haves for 2.0](https://github.com/osiam/connector4java/milestones/2.0)
- [x] osiam/connector4java#117
- [x] osiam/connector4java#139
- [ ] osiam/connector4java#140
- [x] osiam/connector4java#142
- [ ] osiam/connector4java#143
- [ ] osiam/connector4java#155
- [x] osiam/connector4java#170
# [addon-self-administration](https://github.com/osiam/addon-self-administration)

[Must-Haves for 2.0](https://github.com/osiam/addon-self-administration/milestones/v2.0)
- [ ] osiam/addon-self-administration#67
- [ ] osiam/addon-self-administration#107
- [ ] osiam/addon-self-administration#119
- [ ] osiam/addon-self-administration#133
- [ ] osiam/addon-self-administration#134
- [ ] osiam/addon-self-administration#135
# [addon-administration](https://github.com/osiam/addon-administration)

[Must-Haves for 2.0](https://github.com/osiam/addon-administration/milestones/v2.0)
- [ ] osiam/addon-administration#45
- [ ] osiam/addon-administration#59
- [ ] osiam/addon-administration#64
- [ ] osiam/addon-administration#69
- [ ] osiam/addon-administration#71
- [ ] osiam/addon-administration#81
- [ ] osiam/addon-administration#82
- [x] osiam/addon-administration#83
- [ ] osiam/addon-administration#87
- [ ] osiam/addon-administration#88
- [ ] osiam/addon-administration#89
- [x] osiam/addon-administration#102

**Comment by tkrille** [comment]
Changes:
- moved #21 to "must haves"

**Comment by wallner** [comment]
Can we add the subjects of the issues somehow?

**Comment by tkrille** [comment]
That sounds like a lot of awful work. Just hover the links and you see the summary.

**Comment by tkrille** [comment]
Added osiam/auth-server#81 and osiam/resource-server#92 to must haves.

**Comment by dacrome** [comment]
Changes:
- moved osiam/addon-administration#64 to "must haves"

**Comment by dacrome** [comment]
Added link to all Must-Have titles to the milestones of the projects

**Comment by dacrome** [comment]
Removed closed issue https://github.com/osiam/resource-server/issues/67 from resource-server and added created issue #57 to must-haves of osiam

**Comment by dacrome** [comment]
Moved bintray issue from auth- and resource-server to osiam

**Comment by dacrome** [comment]
Updated because issues moved from auth- and resource-server to this repo

**Comment by tkrille** [comment]
Moved  #82 #81 #72 #73 #67 #59 to "Not necessarily"

**Comment by tkrille** [comment]
Moved #39 #41 to "Not necessarily"

**Comment by dacrome** [comment]
Only list "Must-Haves", removed all from "Not necessary" and "Not sure"

**Comment by dacrome** [comment]
Removed scim-schema issues because the scim-schema is no longer maintained.

**Comment by dacrome** [comment]
I close this issue because we can [list all relevant issues and PRs by milestone 3.0](https://github.com/osiam/osiam/milestones/v3.0)
